In [8]:
import numpy as np

In [51]:
a=np.array([[1,8,3],[5,6,7]])
print(a.shape)

(2, 3)


In [71]:
b=np.array([1,2,3,5,7])
print(a.ndim)

2


In [72]:
print(b.dtype)

int64


In [73]:
print(a[1,1])

6


In [74]:
r=np.arange(0,10,2)
print(r[1:16])

[2 4 6 8]


In [75]:
print(a+5)

[[ 6 13  8]
 [10 11 12]]


In [76]:
print(a*2)

[[ 2 16  6]
 [10 12 14]]


In [77]:
print(a+b[0])

[[2 9 4]
 [6 7 8]]


In [78]:
print(np.dot(b,b))

88


In [79]:
print(np.sum(a))

30


In [80]:
print(np.mean(b))

3.6


In [82]:
print(np.sqrt(b))

[1.         1.41421356 1.73205081 2.23606798 2.64575131]


In [89]:
x=np.arange(8).reshape(4,2)
print(x.T)

[[0 2 4 6]
 [1 3 5 7]]


In [94]:
df.read

NameError: name 'df' is not defined